# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing these this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
gems:
#  - octopress-paginate
  - jekyll-paginate
  - jekyll-lunr-js-search
  - classifier-reborn

url: "https://sopadebits.com" # the base hostname & protocol for your site
port: 4000
baseurl: "/" # the subpath of your site, e.g. /blog

title: Sopa de bits
logo: /images/avatar.jpg
introduction: A blog about data, information and IT, by <a href="https://marioalberich.com" target="_blank">Mario Alberich</a>
description: A blog about data, information and IT, by Mario Alberich
keywords: >
  information science, technology, statistics, estadistica, documentacion, informatica,
  machine learning
static_pages:
  en-la-cocina: "En la cocina"
  contacto: "Contacto"
  descargas: Descargas

author:
  name: Mario Alberich
  profile_page: en-la-cocina
  image: images/mario-alberich.jpg
  feed: feed.xml
  twitter_username: sopadebits
  linkedin_username:  marioalberich
  github_username:  malberich

excerpt_separator: "<!--more-->"
google_analytics:
  tracking_code: UA-3459440-1


# Build settings
markdown: kramdown
profile: true
# lsi: true
show_drafts: false
permalink: /:title
# theme: minima


# Configuration for the pagination page
paginate: 10
paginate_path: "/page:num"