name: Generate tag pages

on: [push]

jobs:
  tagging:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Remove old categories and tags"
        run: |
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${GITHUB_ACTOR}@sopadebits.github.io
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          if [ -d "tag" ];then
            git rm ./tag/*
          fi
          if [ -d "category" ]; then
            git rm ./category/*
          fi
          # touch ./tag/placeholder
          # touch ./category/placeholder
          # git add ./tag/placeholder
          # git add ./category/placeholder
          git diff-index --quiet HEAD || git commit -am "Removed old categories" && git push github HEAD:${GITHUB_REF}
      - name: Install dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip3 install frontmatter==3.0.6 python-slugify==4.0.0 PyYAML==5.1
      - name: Regenerate tag files
        run: |
          git pull github ${GITHUB_REF} --ff-only

          python3 scripts/regenerate_tags.py
          git diff-index --quiet HEAD || git commit -am "Updated tags and categories"
          git push github HEAD:${GITHUB_REF}
