name: Build lektor

on: [push]

jobs:
  lektor:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.6]
    steps:
      - uses: actions/checkout@master
      - uses: actions/setup-python@master
        with:
          python-version: ${{ matrix.python-version }}
      - name: "Install dependencies"
        run: |
          python3 -m pip install --upgrade pip
          pip3 install \
            frontmatter==3.0.6 \
            Jinja2==2.11.2 \
            joblib==0.14.1 \
            Lektor==3.1.3 \
            pandas==1.0.3 \
            python-slugify==4.0.0 \
            PyYAML==5.1 \
            scikit-learn==0.22.2.post1 \
            scipy==1.4.1 \
            sklearn==0.0 \
            text-unidecode==1.3 \
            watchdog==0.10.3 \
            Werkzeug==1.0.1
      - name: "Build"
        run: |
          git config --global user.name ${GITHUB_ACTOR}
          git config --global user.email ${GITHUB_ACTOR}@sopadebits.github.io
          git remote add github "https://$GITHUB_ACTOR:$GITHUB_TOKEN@github.com/$GITHUB_REPOSITORY.git"
          git pull github master
          if [ -d "build" ];then
            git rm -rf ./build/
          fi
          git commit -m "Removed old build" ./build/
          mkdir ./build
          cd sopadebits-lektor
          python3 -m lektor build --output-path ../build
          cp ../CNAME ../build/
          cd ..
          git add build/
          git commit -m "Page build ${GITHUB_RUN_ID}" build/*
          git push github master
          git pull --ff-only github master
          git subtree push --prefix build github gh-pages
